### ISSUE TITLE
FR: submodule hook management

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#1]
It would be nice to be able to configure hooks to be placed in each new repo after it is "git meta open"ed.

**Comment by abliss** [comment]
One nice way to do this would be:
1. allow the user to create a directory .git/submodule_template in the meta dir
2. At  ["NodeGit.Repository.initExt(subRepoDir"](https://github.com/twosigma/git-meta/blob/8ef82864afbcd65ed1aae2e5b86d768629d5c837/node/lib/util/submodule_config_util.js#L327) , add a `template` option:
http://www.nodegit.org/api/repository_init_options/

**Comment by bpeabody** [comment]
I don't know if it's a problem with NodeGit or libgit2, but the `templatePath` option is not being respected. I will wire this behavior up manually for now but leave the issue open until I've created an upstream issue.

**Comment by bpeabody** [comment]
Actually, this is not a dupe but it is done.
