### ISSUE TITLE
`rebase` fails when there are new files in sub-repos

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#105]
Fixing this is going to require a patch to libgit2, which sees new files in a sub-repo as changes to the workdir.

Alternatively, we could attempt to stash the new files in the meantime as a workaround.

**Comment by bpeabody** [comment]
Verified that `git rebase` itself does not have this behavior.

**Comment by novalis** [comment]
Can you give more detailed repro instructions?  I have written a test for libgit2 which does the following:
A repo contains a submodule foo.  The submodule is initialized.  I add a new untracked file, "foo" to the submodule's directory.  Then I try to rebase a change which does not touch the submodule top the current state.  This works.

**Comment by jhedwardyang** [comment]
Bump -- this is a pretty big pain point when trying to rebase changes

**Comment by bpeabody** [comment]
I'll see if I can provide repro steps.

**Comment by novalis** [comment]
BTW when trying to repro this on a manually-created repo, I hit #141.  LOL.

**Comment by bpeabody** [comment]
Nice!

**Comment by novalis** [comment]
https://github.com/libgit2/libgit2/pull/4151
