### ISSUE TITLE
libgit2 crawls unopened submodule directories needlessly

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#107]
Especially on diff operations which are used in almost every function.  @abliss has noticed this using `strace`. The performance hit isn't as bad as the O(N^2) problems we are addressing, but it still adds quite a bit of unnecessary overhead, especially on slow filesystems with many submodules.

We need to submit a patch to libgit2 to ignore the directories of closed submodules.

**Comment by novalis** [comment]
I don't understand why it is wrong to crawl uninitialized submodules.  How else would you detect a change which converted a submodule to a directory?

**Comment by bpeabody** [comment]
Submodules already are directories; to convert them back you'd have to touch the `.gitmodules` file, which doesn't require trawling the directory tree. On the other hand, I guess you would have to do this traversal to see if the user added random files in the tree. Maybe this can't be avoided.

**Comment by bpeabody** [comment]
Working around this by having status ignore the meta-repo by default.
