### ISSUE TITLE
git meta push currently doesn't work if submodules and meta repository don't have the same remote name

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#111]
meta remote: upstream
submodules remote: origin

Cannot git meta push -s upstream because submodules do not contain upstream.

**Comment by bpeabody** [comment]
I think that, in fact, `git-meta push` should ignore remotes configured in the submodule and always resolve the submodule URL against the remote being pushed to in the meta-repo -- protecting against potential misconfiguration.

**Comment by bpeabody** [comment]
Fix pending in https://github.com/twosigma/git-meta/pull/135 and related PR https://github.com/twosigma/git-meta/pull/139.
