### ISSUE TITLE
git meta open doesn't run post-checkout hook

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#113]

**Comment by bpeabody** [comment]
I already had https://github.com/twosigma/git-meta/pull/114 in the works; it may fix the problem as it uses `checkout` instead of `reset` in `openOnCommit`. However, do you expect this hook to run on `reset` too?

**Comment by abliss** [comment]
I do not expect it to run on reset.

**Comment by bpeabody** [comment]
OK, then this PR should fix the problem for you.

But! What kind of action would be critical to happen on checkout but not on reset? I think this type of omission is part of what feeds my skepticism of trying to maintain state through the use of hooks.
