### ISSUE TITLE
`NodeGit.Repository.initExt` does not honor `templatePath` option

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#122]
Possibly an issue with libgit2, but I think it's more likely a problem with nodegit not propagating the argument.

**Comment by novalis** [comment]
Yes it does -- you just need to pass NodeGit.Repository.INIT_FLAG.EXTERNAL_TEMPLATE in the 'flags' field of the options.

I'd like to fix the nodegit docs on this, because it too me way to long to figure out, but I can't figure out how they are generated yet.

**Comment by novalis** [comment]
https://github.com/nodegit/nodegit/pull/1172

**Comment by bpeabody** [comment]
I think in some cases, the nodegit API is too thin a wrapper around libgit2. Here, it would be reasonable for the presence of `templatePath` to imply that the user wants to use it :)

**Comment by novalis** [comment]
Yeah, that seems pretty reasonable.  I'll ask if they think that's reasonable.
