### ISSUE TITLE
Come up with a story for Git hooks.

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#124]
Libgit2 doesn't want to tackle this problem, so we'll have to come up with story.

https://github.com/libgit2/libgit2/issues/964
https://github.com/libgit2/libgit2/pull/3824

**Comment by bpeabody** [comment]
I've said it before and I'll say it again: I don't like hooks. All the things we need to do with them are for hacks, and I think they lead to brittle solutions. I suggest that instead of using hooks, we add code to, e.g. build scripts that to do the work on demand.
