### ISSUE TITLE
Enable public repo Travis CI

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#133]
To get this working on this repository, we need to get the "Travis CI" (non-Pro) application approved on the GitHub organization.

See details regarding permissions that the application requires - https://docs.travis-ci.com/user/github-oauth-scopes/

**Comment by kgraney** [comment]
Isn't this still an issue?  It's confusing to have a public facing git repo with a `.travis.yml` that isn't actually triggering Travis in the official project.

**Comment by novalis** [comment]
It's a "wontfix" since the policy is that Travis is forbidden for repos in this organization.  You can run Travis against your fork using this repo's .travis.yml.

**Comment by kgraney** [comment]
That feels wrong.  I think it's worth considering revisiting that policy, moving the project to a different organization, or finding a different CI system allowed by the policy.  There are good things being missed out on by this oversight.

**Comment by jhedwardyang** [comment]
Policy was changed, and Travis is now running.

**Comment by kgraney** [comment]
👍
