### ISSUE TITLE
nodegit/libgit2: if you abort a rebase in-progress in a submodule, it corrupts the sub-repo

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#151]
Such that the `.git/modules/$sub-repo` is no longer a valid git repository.

I will work around the problem for now.

**Comment by novalis** [comment]
[test-rebase.zip](https://github.com/twosigma/git-meta/files/646783/test-rebase.zip) is my attempt to repro.  While it's true that the abort leaves HEAD pointing to the wrong thing (the raw sha instead of the branch), the abort is otherwise successful, and does not appear to corrupt the submodule.

**Comment by novalis** [comment]
oops, prev version of zip forgot the js file

**Comment by bpeabody** [comment]
I can no longer recreate.
