### ISSUE TITLE
`checkout` doesn't work

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#162]
Fails with "Object to checkout does not match repository."

@jhedwardyang: I haven't been able to recreate this yet, so I am going to assign it to you for now.

**Comment by jhedwardyang** [comment]
5 open submodules seems to be a magical number!

**Comment by bpeabody** [comment]
@jhedwardyang I think it may be more than *just* the 5 open subs. If you were able to reproduce this on your laptop, could you upload a zip of the state from which the problem can be reproduced? I tried:

```bash
$ write-repos -o "a=B|b=B|c=B|d=B|e=B|x=S:C2-1 s=Sa:1,t=Sb:1,u=Sc:1,v=Sd:1,w=Se:1;Bmaster=2;C3-2;Bfoo=3;Os;Ot;Ou;Ov;Ow"
$ cd x
$ git meta checkout foo
$ git meta checkout master
```
And all went well.

**Comment by bpeabody** [comment]
Closing this pending recreation steps.
