### ISSUE TITLE
consider a templating system for `git meta new`

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#185]
Git abhors an empty repository and users generally want to create repositories with some regular pattern.

Investigate creating a templating system to prepopulate new repositories, staging the created files.

**Comment by novalis** [comment]
IIRC, git already has a templating system for repos created with git init.

On January 25, 2017 10:37:06 AM EST, Brock Peabody <notifications@github.com> wrote:
>Git abhors an empty repository and users generally want to create
>repositories with some regular pattern.
>
>Investigate creating a templating system to prepopulate new
>repositories, staging the created files.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/twosigma/git-meta/issues/185

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bpeabody** [comment]
That sounds ideal

**Comment by bpeabody** [comment]
Actually, that's a little insufficient. We need a templating system that is creates files parameterized by (a) the name of a project and (b) some user-specified value (e..g, "C++"). The more I think about it though, such a thing might be outside the scope of a template invoked automatically by git-meta.
