### ISSUE TITLE
comparison with git-subrepo

### ISSUE THREAD

**Issue by NicolasRouquette** [twosigma/git-meta#201]
This is an interesting approach; I'd like to see the comparison include [git-subrepo](https://github.com/ingydotnet/git-subrepo)

**Comment by bpeabody** [comment]
Interesting; I'll take a look. I didn't evaluate this one when we first started this project (you can see a list of the alternatives we did look at here: https://github.com/twosigma/git-meta/blob/master/doc/architecture.md).

**Comment by bpeabody** [comment]
Here's how I understand the mission of `git-subrepo` and how its purpose differs from that of `git-meta` (after quick read-through of its README; I don't claim to fully understand it yet):

The goal of `git-subrepo` is to provide a better implementation of the solution to the problem that git-submodules are intended to solve -- referencing specific states of external repositories inside "your" repository. I think it's an interesting approach to the problem and looks like it has a much friendlier UI than plain git-submodules.

The goal `git-meta`, on the other hand (and its mission has admittedly been evolving), is to use git-submodules to implement a *mono-repo*. A `git-meta` repository is a single unit decomposed into sub-repositories as an optimization.

A key difference being that the sub-repos in `git-subrepo` are considered to be external, whereas in `git-meta` they're considered to be different sub-parts of the same unit. E.g., `git meta commit -a` stages and commits files in all (modified) sub-repos, and then a commit in the meta-repo, whereas (if I understand correctly), with `git subrepo commit`, the purpose is to set/update what state from a sub-repo is being referenced in the containing repo.

Does this sound right?

We're actually taking the concept of a `git-meta` repo being a single repository one step further with the [omega repo](https://github.com/twosigma/git-meta/wiki/The-Omega-Repo) proposal we're currently discussing. In this case, the sub-repos and containing (meta) repo area actually one repo.
