### ISSUE TITLE
change synthetic-meta-refs to include submodule name in their name

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#217]
We're going to need this to make synthetic-meta-ref pruning a tractable problem in the omega repo.

**Comment by novalis** [comment]
I think the pruning algorithm should be:
For each durable ref in the meta repository, find the value for each subrepo's commit.  This is the reachable set.  For each rev in the reachable set, delete the synthetic metarefs for all of its ancestors.

So I don't understand why changing the ref format is necessary?

**Comment by bpeabody** [comment]
I think there is a little more to it. If I, e.g., made a branch, pushed it, then deleted it, there would be "dangling" refs that would not be caught. I think the algorithm needs to be (1) build reachable set as described, (2) delete refs not in reachable set. This is more expensive than what you described but still something that can be done in linear (w.r.t. the number of refs) time. The algorithm I had in mind was: delete all refs not reachable from other refs. This would be O(N^2) w.r.t. the number of refs, so I wanted to be able to phrase it as "for each submodule, look at the set of meta-refs and delete the ones that aren't reachable from other refs for that submodule".
