### ISSUE TITLE
Aborting a rebase started in DETACHED_HEAD borks repo

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#225]
- start in detached head
- cause rebase to find a conflict
- abort the rebase
- .git/HEAD gets updated to `ref: HEAD` and borks repo

(should probably get updated to ORIG_HEAD?)

**Comment by bpeabody** [comment]
I'm pretty sure this is going to end up being a bug for libgit2; the only thing we're doing to the meta-repo is calling `Rebase.abort` on it.

**Comment by novalis** [comment]
I'll take a peek at libgit2 on this.  I'm feeling some deja vu on this -- I wonder if I already tried this and was unable to repro, or if I just never finished patching it or something.

**Comment by novalis** [comment]
Oh, maybe I looked at the code and was like, "but there's a test that claims to be for precisely that!" 

But the test's name is a lie.

**Comment by bpeabody** [comment]
@novalis we had this: https://github.com/twosigma/git-meta/issues/151, and indeed we were unable to reproduce. It brings up an interesting point though, that rebases in submodules are almost always from a detached head state.

**Comment by novalis** [comment]
So, by making the test actually test a detached-head state, I can get a *different* bug...

**Comment by bpeabody** [comment]
@novalis more detail on the different bug? Also, do you think that if we fix this we will address the problem originally affecting our user?

**Comment by novalis** [comment]
It looks like libgit takes the "onto" as the initial state to return the repository to after the rebase is aborted.  That's not correct -- it ought to be the original HEAD.

**Comment by novalis** [comment]
Hm, actually, that's what regular git rebase does.  Confusing.  Also not sure what the difference between rebase-apply/orig-head and ORIG_HEAD is.

**Comment by novalis** [comment]
I wonder if the problem is that head-name gets set to HEAD and this causes badness.  Not sure how that would happen, but it seems like the likeliest explanation.  Proposal: we should locally patch libgit2 to refuse to write "HEAD" into head-name.  Next time it tries to do that, it'll abort, and we'll be able to understand what state causes it to happen.
