### ISSUE TITLE
git meta commit --amend incorrectly displays "<submodule> has new commits"

### ISSUE THREAD

**Issue by shaoster** [twosigma/git-meta#234]
Repro:
- Create a new meta repo.
- open a submodule.
- create a new commit in the submodule.
- git meta commit -a -m "foo"
- soft reset back to baseline.
- git meta commit -a --amend -m "bar"

git meta status reports the correct issue:
"(submodule, on old commit)"

**Comment by bpeabody** [comment]
After discussion with @shaoster , I believe this issue is caused by a combination of confusion/user error.

**Comment by bpeabody** [comment]
Completely redid this.
