### ISSUE TITLE
Allow separate commit messages for each submodule in `commit`.

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#238]
E.g., would be split out like:

```
# <*> enter meta-repo message above this line; delete to commit only submodules
# On branch master.
# -----------------------------------------------------------------------------

# <s> enter message for 's' above this line; delete this line to skip committing 's'
# Changes to be committed:
# 	new file:     a
# -----------------------------------------------------------------------------

# <t> enter message for 't' above this line; delete this line to skip committing 't'
# Changes to be committed:
# 	modified:     README.md
#
# Please enter the commit message(s) for your changes.  The message for a
# repo will be composed of all lines not beginning with '#' that come before
# its tag, but after any other tag (or the beginning of the file).  Tags are
# lines beginning with '# <sub-repo-name>', or '# <*>' for the meta-repo.
# If the tag for a repo is removed, no commit will be generated for that repo.
# If you do not provide a commit message for a sub-repo, the commit
# message for the meta-repo will be used.
```

Would also apply to `amend`.

**Comment by bpeabody** [comment]
Here is the prompt syntax I'm going with (there being changes to submodules `s` and `t` in this example):
```

# <*> enter message for the meta-repo above this line; delete to skip
# On branch master.
# -----------------------------------------------------------------------------

# <s> enter message for 's' above this line; delete to skip
# Changes to be committed:
# 	new file:     a
# -----------------------------------------------------------------------------

# <t> enter message for 't' above this line; delete to skip
# Changes to be committed:
# 	modified:     README.md
#
# Please enter the commit message(s) for your changes.  The message for a
# repo will be composed of all lines not beginning with '#' that come before
# its tag, but after any other tag (or the beginning of the file).  Tags are
# lines beginning with '# <sub-repo-name>', or '# <*>' for the meta-repo.
# If the tag for a repo is removed, no commit will be generated for that repo.
# A sub-repo with an empty commit message will inherit the commit message of
# the meta-repo, if it has one.  Commits will not be created for repos with
# empty commit messages.
```

**Comment by novalis** [comment]
"delete to skip" on the meta repository is a little unclear -- what does it mean?

Also the following seems self-contradictory:

"A sub-repo with an empty commit message will inherit the commit message of the meta-repo, if it has one.  Commits will not be created for repos with empty commit messages."

**Comment by bpeabody** [comment]
Re. the first item, how about: "delete this line to skip committing this repo"

Re. the second, how does this sound:
"In general, commits will not be created for repos having empty commit messages. However, when the meta-repo has a commit message, its message will be used by sub-repos for which no message is specified."

**Comment by novalis** [comment]
Wait, so deleting the line for the meta repo would just commit the submodules?  Why not just say that?

Also, I would rather have some special message like "skip" so that it's possible to have a global commit message and yet skip committing certain submodules.  That seems cleaner than having a behavior which means "either don't commit this, or commit this with a default message depending on something somewhere else".

**Comment by bpeabody** [comment]
I will clarify the meta-repo message 

I like the behavior I have with skipping submodules; I think maybe I'm not clarifying it well. The right way to skip a submodules is to delete its tag. I think this is cleaner (and easier)  than having a special message. If you don't provide a message for a submodule, it will use the meta-repo message. The normal usage would be to enter the meta repo commit message, and then selectively remove or alter submodules. 

The warnings about empty commit are just to say that we won't generate commits with empty messages. 

How about instead of clumsily spelling out the unusual situation where there are empty meta- and sub- repo messages, I display a warning about repos that aren't committed due to empty messages?

**Comment by novalis** [comment]
Oh, I see.

On reflection, I'm not sure I want a mode that just commits submodules.  It seems weird to me that "git meta commit" would sometimes create submodule commits without creating a meta commit.  That would be really surprising to me.  I think I would rather just abort in that case, leaving the message in COMMIT_EDITMSG in case the user wants to save it.  This is what git does if the commit message has only comment lines in it.

**Comment by bpeabody** [comment]
How about if people leave the meta-repo message empty, we abort and leave the message in COMMIT_EDITMSG, but allow the commit to go through if the user explicitly deletes the meta-repo tag. Users do seem to want to make sub-repo commits individually at times, so I can imagine them using this feature -- it's not destructive, anyway.

**Comment by novalis** [comment]
OK, that seems legit to me.
