### ISSUE TITLE
FR: git meta checkout -t (tracking)

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#250]
Similar to git checkout -t

**Comment by bpeabody** [comment]
We should also support this, while we're at it:
```
If <branch> is not found but there does exist a tracking branch in exactly one remote (call it <remote>) with a matching name, treat as equivalent to

               $ git checkout -b <branch> --track <remote>/<branch>
```

**Comment by bpeabody** [comment]
Working on making these options work well together -- and like they do in Git, I think I've found a bug in Git. Basically the `--track` option fails to work with an unrelated error message if a sha is specified. For example, if I am in a situation where I can checkout a commit on a new branch, `meh` like this:
```
$ git co -b meh 1f1fa7c63ff15a19789ca7200582ef8c9240e4aa
Switched to a new branch 'meh'
```
And I can also make a new branch, `meh` on HEAD with a tracking branch:
```
$ git co -b meh -t origin/master
Branch meh set up to track remote branch master from origin.
Switched to a new branch 'meh'
```
But if I try to do both at once, it fails:
```
$ git co -b meh -t origin/master 1f1fa7c63ff15a19789ca7200582ef8c9240e4aa
fatal: Cannot update paths and switch to branch 'meh' at the same time.
Did you intend to checkout '1f1fa7c63ff15a19789ca7200582ef8c9240e4aa' which can not be resolved as commit?
```
Clearly, that sha should be resolvable to a commit as it is the exact ID of one. I suspect that the problem is in argument processing. @novalis , does this look like a bug to you?

**Comment by bpeabody** [comment]
Meanwhile, I will proceed with making these options function together as I believe they should.

**Comment by novalis** [comment]
I believe the error message is confusing, but that git is correct to disallow the command.

The -t option does not take a refspec to track. It attempts to figure out the refspec for you.

**Comment by bpeabody** [comment]
I think I disagree. For example, both of these are valid in the same repo, configuring different tracking branches:
```
$ git checkout -b meh -t origin/master
Branch meh set up to track remote branch master from origin.
```
and
```
$ git checkout -b meh -t origin/foo
Branch meh set up to track remote branch foo from origin.
```
If you omit the `-t` option, and the branch name you give isn't directly resolvable, in that case it *will* try to figure out what remote tracking branch to check out and set up, e.g., in the case where there is no local `foo`:
```
$ git checkout foo
Branch foo set up to track remote branch foo from origin.
Switched to a new branch 'foo'
```

**Comment by bpeabody** [comment]
In fact, with the `-t` option, it will refuse to try to figure out the respect. Given the same repo having an `origin/foo`:
```
$ git checkout -b meh -t foo
fatal: Cannot update paths and switch to branch 'meh' at the same time.
Did you intend to checkout 'foo' which can not be resolved as commit?
```

**Comment by novalis** [comment]
I don't think -t affects whether git will figure out that when you said "I want to foo", you meant "I want origin/foo".
