### ISSUE TITLE
implement `stash`

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#251]
A `git meta stash` is a commit whose tree reflects the state of the workdir of the meta-repo (including unstaged commits in submodules) and has the following parent commits:
- the HEAD commit at the time the stash was made
- a commit whose tree reflects staged changes to the meta-repo and staged sub-repo commits
- a commit reflecting the stash commits created for each submodule that required a stash. The tree of this commit reflects the workdir of the sub-repo being stashed. It has one parent, whose tree reflects the state of the index.

The most recent stash is found in `refs/meta-stash`; older stashes are found with the reflog.

 Structure of the meta-repo stash commit:
```
          ,-------------,       ,---------------------,
          |  *git-meta  | tree  |    +Workdir         |
          |    stash    |------>| meta-repo workdir   |
          `-------------'       | (including unstaged |
  parent   0 |  1 |   2 |       | submodule commits)  |
  commits    |    |     |       `---------------------'
             |    |     .
,---------,  |    |      \      ,-------------,
| *HEAD   |  |    |       `---->| *Submodules |
| of repo |<-'    |             `-------------'
`---------'       |                    |
                  V                    | tree
             ,--------,                V
             | *Index |          ,-------------------------,
             `--------'          |  +Submodule Stashes     |
                  |              | identifies stash commit |
             tree |              | for each submodule with |
                  V              | a stash                 |
       ,--------------------,    `-------------------------'
       |       +Index       |
       | meta-repo index    |
       | (indluding staged  |
       | submodule commits) |
       `--------------------'

* -- a commit
+ -- a tree
```

Structure of each sub-repo stash commit referenced by the meta-repo stash (note, these are stored in the respective sub-repos):

```
   ,-----------,
   | *sub-repo | tree  ,-------------------,
   |   stash   |------>|     +Workdir      |
   `-----------'       | state of sub-repo |
parent 0|    1|        | working directory |
commits |     |        `-------------------'
        V     V
,---------,  ,--------, tree   ,-------------------,
| *HEAD   |  | *Index |------->|      +Index       |
| of repo |  `--------'        | state of sub-repo |
`---------'                    |       index       |
                               `-------------------'
```

Additionally, each sub-repo stash commit is rooted (against gc) by a synthetic-meta-ref named `refs/sub-stash/$<commit id>`.

**Comment by novalis** [comment]
I don't understand what the tree of the top-level stash commit is supposed to look like, or the trees of the various parent commits for the submodules?  Do we mean to stash child  repo data  in the meta?

**Comment by bpeabody** [comment]
The tree of the top-level stash corresponding to the workdir will have the state of the workdir of the meta-repo. This tree includes unstaged changes to the meta-repo itself as well as unstaged commits in open sub-repos.

I do not intend to stash child repo data in the meta-repo. One of the commits mentioned in the meta-repo will reference the stash commits of the sub-repos though.

**Comment by bpeabody** [comment]
I can see how this is confusing though. Maybe a little ascii art would help?

**Comment by novalis** [comment]
Ascii art always helps.

**Comment by bpeabody** [comment]
Let's see if that makes more sense.

**Comment by bpeabody** [comment]
For the first cut, `stash` will have the following restrictions, in order of most to least likely to be lifted:

- new (sub-repo) commits (staged and unstaged) will be ignored, that is, the stash will reflect only changes to the index and workdir of open submodules
- changes to the index and workdir of the meta-repo (other than sub-repos) are ignored -- this restriction simplifies the operation, improves performance (we don't need to crawl the workdir of the meta-repo), and generally we do not expect users to manipulate the meta-repo
- submodule configuration changes (i.e., additions, removals, and URL changes) will be ignored and/or disallowed -- to avoid dealing with conflicts to the `.gitignore` file

In any case, the stashes I write will be forward-compatible such that they will continue to work when/if new capabilities are added.

**Comment by bpeabody** [comment]
Note that the bulk of the logic for stashing sub-repos can be implemented in terms of libgit2's `stash`; we just need to tie the sub-repo stashes together. (I write this after having already implemented the save logic by hand; will not roll forward with my implementation).

**Comment by bpeabody** [comment]
For now, I'm going to store just one child of the meta-repo commit -- the one with the submodule stashes. Git itself will not stash submodules, so I will have to do those by hand if I want to be able to stash staged/workdir submodule commits, but I think I will want to use `libgit2` to stash the actual content of the meta-repo, if I ever do.
