### ISSUE TITLE
FR: locally manage submodule refs for omega repos

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#258]
In the meta repo, suppose I've set up some branches I care about:
```
remote.origin.fetch=+refs/heads/master:refs/remotes/upstream/master
remote.origin.fetch=refs/heads/myteam/dev:refs/remotes/myteam/dev
remote.origin.fetch=refs/heads/myteam/release:refs/remotes/myteam/release
```

Now I have an omega repo, and I've opened a few codebases:
```
git meta open client1/
git meta open server2/
```

Now I want to know, for example: what's the difference between `myteam/dev` and `myteam/release`, only in these codebases? `git meta diff` can offer some tools for this, but what I really want is to use the full suite of git command-line and gui tools (for example, `git log --graph --decorate`) in the submodules.

So my proposal is that "sometimes" (perhaps, on each `git meta pull` or `git meta open`), we would create (local-only, totally-unpushable and un-fetchable) "submodule tracking branches". So e.g. we'd fetch `origin/master` in the meta, lookup the sha1 for `client1` in its tree, and set `refs/heads/master` (or `refs/remotes/origin/master`?) to point to that sha1 inside the `client1` local submodule.  Then the same for every ref in the meta's `remote.origin.fetch` values.

**Comment by bpeabody** [comment]
"(local-only, totally-unpushable and un-fetchable)" -- I wouldn't worry too much about making them unpushable or unfetchable. 

1. Git-meta itself will never push or fetch sub-repo refs.
2. We have to rely on server-side hooks to prevent ref littering in important forks, anyway.
3. If users feel like pushing goofy refs inside their personal forks with "raw" git commands I don't want to stop them; they may have (good?) reasons.

**Comment by bpeabody** [comment]
"So my proposal is that "sometimes" (perhaps, on each git meta pull or git meta open)"

That sounds reasonable. At the very least we could can start by making a `git meta submodule` command to set these refs.

**Comment by abliss** [comment]
> with "raw" git commands I don't want to stop them;

right, we won't try to stop them, but the expectation will be that there is no sensible place to push or pull them, so they are unlike regular branches people are used to. (in a gitlab "Psi Repo" setup, serverside forking will be disabled for the "subs" repo, and only synthethic refs can be pushed to it.)

**Comment by jhedwardyang** [comment]
I like the idea of fetching into `refs/remotes/origin/myteam/dev` - won't be fetchable (since the branch doesn't exist in origin), and won't create cluttering branches for the average user.  

A possible downside is the power git user may get confused, since the branch doesn't exist upstream in `refs/heads`, but it'll exist in `refs/remotes`.

**Comment by bpeabody** [comment]
I added a command to make these references in this PR: https://github.com/twosigma/git-meta/pull/261. This PR will add a command to create these refs.

For now, I think this is all I want to do here. I'm a little suspicious of magic in general. I don't think it's onerous for a user to run a command like this before doing research, and by making it an explicit command I think we avoid potential confusion.

**Comment by abliss** [comment]
Maybe we could push this a little further without too much unwanted magic?
1) "git meta submodule addrefs" could also move the HEAD of each submodule onto the appropriate newly-created branch (some tools and [some people] find detached heads scary)
2) "git meta checkout" could also move the submodule onto that branch, IF it already exists AND it points to the correct commit.
3) "git meta pull" could also update the addrefs if they're added.

You still have the problem that people can "git fetch" and then the submodule branches are out-of-date and they can get confused.

**Comment by jhedwardyang** [comment]
How about creating a `git meta fetch` that will generate into `refs/remotes/origin/<meta branch name>`. They won't get used if we don't have branches upstream in the submodule and you can update them with `git meta fetch origin`?

**Comment by bpeabody** [comment]
I like all these suggestions.

To be honest: "some tools [and some people] find detached heads scary" -- I used to be one of these people.
