### ISSUE TITLE
Implement `git meta diff`

### ISSUE THREAD

**Issue by william-clarke** [twosigma/git-meta#259]
I have two meta branches, that have most of the same commits. I would like to know what their diff is, so I can be sure that all the important changes are reflected in both branches. Therefore, I would like to be able to `git meta checkout $branch1; git meta diff $branch2`

**Comment by william-clarke** [comment]
(or `git meta diff $branch1 $branch2`)

**Comment by william-clarke** [comment]
Sorry, duplicate of #63

**Comment by bpeabody** [comment]
No worries, @william-clarke  I will prioritize this work if it's something you want.
