### ISSUE TITLE
Bug: git meta with some bad args leaves good args in bad state

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#26]
In a fresh meta clone, run "git meta open asdf foo/bar" where foo/bar is a valid submodule and "asdf" is a typo.

The command fails with "Error: No submodule named 'asdf'" but now your submodule foo/bar is (a) "open", in the sense that it has a .git directory, but (b) broken, in that it has no files checked out and no local branches.

**Comment by bpeabody** [comment]
This was fixed a while back, but noticed that bad paths still cause an erroneous error message; fixed in https://github.com/twosigma/git-meta/pull/193.
