### ISSUE TITLE
UX: warn when amending someone else's commit

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#269]
A user just did git meta commit --amend and got an error that some repositories didn't match.  The user should have expected this, as they were accidentally trying to amend someone else's commit.  Oops!

I think git meta should have a couple of UX fixes here:
1. When amending a commit fails because of "not our commit" issues, we should put bold warning if the committer of the to-be-amended commit does not match our identity.  "WARNING: You are amending a commit by A U Thor <a.uthor@example.com> -- did you really mean to use --amend?" 

2. (maybe) We should prevent amending commits by another author unless the user passes the --amend-other flag. This will prevent cases where commit --amend accidentally works.  This might be less urgent, and it's not clear that it's correct; git usually permits this sort of foot shooting.  Maybe a feature flag, which we could turn on by default inside our company?

**Comment by bpeabody** [comment]
This has completely changed in the new (long, unreleased) `amend`. It would now give you an error like:
```
Cannot amend because the signatures of the affected commits in the
following sub-repos do not match that of the meta-repo:
    s
You can make this commit using the interactive ('-i') commit option.
```
Then, when run with `-i`, it will show you the detailed information about the original author, etc.

**Comment by novalis** [comment]
Oh, thanks.  I wonder if the word 'signature' is a bit confusing and could be replaced with 'author name/email', and if the message about the repo could say, 's (last commit by A U Thor <author@example.com>).

**Comment by bpeabody** [comment]
Yeah, good call. I'll leave this issue open for that change.
