### ISSUE TITLE
git meta merge is not working as expected

### ISSUE THREAD

**Issue by s-xiang** [twosigma/git-meta#288]
I reproduced the bug:
1. In my branch (shihui/0601) make a conflict change in codebase 1, and make a ff change in codebase2. 
2.  git fetch upstream shihui/0601
3. git meta merge FETCH_HEAD -m "merge from shihui/0601"
After step 3, I got this output:  
Submodule codebase1 is conflicted.
4. When i tried to cd to codebase1, I did 'git status', and I got clean subrepo, no conflict changes showed up.

**Comment by bpeabody** [comment]
@s-xiang so you expected to see conflicted files, but there weren't any?

**Comment by s-xiang** [comment]
@bpeabody Yes, nothing show up in the subrepo, it was saying" everthing up to date"

**Comment by bpeabody** [comment]
K. I'll see if I can recreate.

**Comment by abliss** [comment]
So this is probably fixed now?

**Comment by bpeabody** [comment]
@s-xiang : can you verify?

**Comment by bpeabody** [comment]
Have done a lot of work on merge since this; will assume fixed until have new repro steps.
