### ISSUE TITLE
git meta pull can't find upstream branch if no local tracking branch

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#289]
```
$ git meta pull --rebase upstream foo/mybranch
The meta-repo does not have a branch named foo/mybranch in the remote upstream.
$ git ls-remote upstream foo/mybranch
23aa143680e378cd1dbf212c583088c6deccf7c6        refs/heads/foo/mybranch
$ git config --add remote.upstream.fetch +refs/heads/foo/mybranch:refs/remotes/upstream/foo/mybranch
$ git fetch
$ git meta pull --rebase upstream foo/mybranch
# works now
```

**Comment by jhedwardyang** [comment]
Looks like pull just checks https://github.com/twosigma/git-meta/blob/master/node/lib/util/git_util.js#L264

**Comment by bpeabody** [comment]
Problem is that `git meta pull` does a "normal" fetch which is (a) inefficient when a repo is configured normally: to fetch all branches by default and (b) fails to work when a repo is configured like @abliss 's: to fetch only `master` by default.
