### ISSUE TITLE
FR: `git meta status` should inform about ancestors

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#30]
1. `git meta open foo/bar`
2. `git pull`
3. `git meta status`

If I pull in meta changes which update foo/bar, but don't update foo/bar itself for some reason, then `git meta status` tells me "Head is on abc, which is not a descendent of the expected commit: def.". If in fact abc is an _ancestor_ of def, then I would expect it to tell me that (and probably suggest that I run `git submodule update foo/bar`).

**Comment by bpeabody** [comment]
I believe this to be fixed.
