### ISSUE TITLE
push should deduce remote and target branch from configured tracking branch (including pushDefault) when present

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#304]
This logic is already wired up for pull, but push still uses the old broken behavior of defaulting to `origin` as the remote and the current branch as the target.

**Comment by abliss** [comment]
I would say that "git meta push" should repsect the settings in "push.default". It seems to be hard-wired to always do "upstream", but I would think that "simple" (which is the default since Git 2.0) makes more sense.

**Comment by bpeabody** [comment]
See the "push.default" section in https://git-scm.com/docs/git-config for more information.
