### ISSUE TITLE
`git meta root` should not readlink -f

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#318]
```
ln -sf /long/path/to/my/root ~/root
cd ~/root
git meta root
```
EXPECTED: `/home/$USER/root`
ACTUAL: `/long/path/to/my/root`

**Comment by bpeabody** [comment]
I don't think this is possible or correct. The running process doesn't know that you "should" be in the short path. For example,

```
$ git rev-parse --show-toplevel
```
and
```
$ echo 'console.log(process.cwd())' | node
```
Will both reflect `/long/path/to/my/root`.

**Comment by abliss** [comment]
You're right. TIL the difference between the bash pwd builtin and /bin/pwd: https://stackoverflow.com/questions/3134479/shell-built-in-pwd-versus-bin-pwd
