### ISSUE TITLE
git meta rebase --abort closes submodule with conflict (and leaves it in a rebasing state)

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#362]
Aborting a conflicted `git meta rebase` causes the conflicting submodule to get closed. 
On re-open, it is also left in a rebasing state (but no conflict, surprisingly).

```
$ git meta rebase --abort
Set HEAD back to <sha>.
$ ls submodule/foo
<empty>
$ git config --get submodule.submodule/foo.url
<non-empty>
$ git meta open submodule/foo
$ git status
rebase in progress; onto <sha>
You are currently rebasing.
  (all conflicts fixed: run "git rebase --continue")
```

**Comment by bpeabody** [comment]
That's wild. I'm just calling `NodeGit.Rebase.abort` on the meta-repo and then all submodules. I wonder if it's doing something bad when the abort is called on the meta-repo.

**Comment by bpeabody** [comment]
I can recreate this with:

```bash
$ write-repos 'a=B:Ca-1 foo=bar;Cb-1 foo=moo;Ba=a;Bb=b|x=U:Cx-2 s=Sa:a;Cy-2 s=Sa:b;Bfoo=y;Bmaster=x' 
$ cd x
$ git meta rebase foo
$ git meta rebase --abort
```

**Comment by bpeabody** [comment]
This looks like a bug in `NodeGit.Rebase.abort`; that call is closing the submodule for that reason. Handing this over to @novalis to see if he can upstream a fix.

**Comment by novalis** [comment]
@bpeabody asked me to wait on this because we might be redoing the sequencer code anyway.
