### ISSUE TITLE
working tree and index get out-of-sync

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#365]
This leads to funny problems like:
$ git meta checkout mybranch
Unable to checkout submodule blort: 1 conflict prevents checkout.
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   blort

$ git diff
[no changes]

Doing 'git checkout HEAD -- blort' fixes it.  

I'm not sure how we get into this state, but it's happened to our users twice.

**Comment by bpeabody** [comment]
They can get out of synch in many ways, e.g., if a user makes a new commit in a submodule. Maybe this ticket should be to make `git meta checkout` work in that situation? I'm not really sure that it should.

**Comment by novalis** [comment]
Sorry, edited title to explain what's actually up (I think)

**Comment by bpeabody** [comment]
Yeah, so the HEAD of a submodule is what git considers to be the working tree for it. If you have a commit in the HEAD of a repo that doesn't match what's in the index (of the containing repo), Git considers there to be working tree modifications for that subrepo.

**Comment by novalis** [comment]
It's happening to people in submodules that they didn't touch.

**Comment by bpeabody** [comment]
Will need reproduction steps (e.g., at least what command causes the problem) then.

**Comment by bpeabody** [comment]
I suspect this is fixed now that we no longer do a real checkout in the meta-repo.
