### ISSUE TITLE
`TreeBuilder.write` segfaults

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#373]
I think I know what the problem is now. Easies repro step is to run the `generate-repos script included in git-meta:

```bash
$ node/bin/generate-repo -b 1000 foo
```

It looks to me that the problem is the `git_tree_entry` objects being returned by `git_tree_builder_insert` are being freed before they are used by `git_tree_builder_write`:

My suspicion is:
1. `Treebuilder.insert` returns a wrapper for a `git_tree_entry` object.
2. I ignore this object.
3. The object is collected at some point
4. when `Treebuilder.write` is called, one or more entries are dead.

**Comment by novalis** [comment]
Actually ran out of memory:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x10c9ffc [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, bool, int, bool) [node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::MacroAssembler*, v8::internal::CompilationInfo*) [node]
 7: v8::internal::FullCodeGenerator::MakeCode(v8::internal::CompilationInfo*) [node]
 8: 0xb45a40 [node]
 9: 0xb47d9d [node]
10: 0xb4f74e [node]
11: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [node]
12: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [node]
13: 0x3e5584d060c7
Aborted
```

Does it really use more than 14GB?  If so, how much more?

**Comment by bpeabody** [comment]
That’s curious. I think it must be leaking.

**Comment by bpeabody** [comment]
On my machine it segfaults before the process has even 4GB allocated.

**Comment by bpeabody** [comment]
Ah, @novalis, you see that on the CL? I thought you'd seen that from the debugger. I do see that error if I force JS to run out of memory, but what I'm seeing is just `Segmentation fault: 11` with no stack.

**Comment by novalis** [comment]
My node is v6.11.1 -- you?

**Comment by bpeabody** [comment]
v8.1.3

**Comment by novalis** [comment]
On 8.6, which was the easiest 8.x to install, I've been running for like six hours without a segfault.

**Comment by bpeabody** [comment]
Interesting. I guess it's not too critical since the program will pick up where it left off if restarted anyway.

**Comment by novalis** [comment]
Also, after some length of time (hours), it seems to hang for me.  Restarting it works, but then it hangs again.

**Comment by bpeabody** [comment]
I worked around this (and it was really only an issue for the "stitcher", not mainline git-meta use).
