### ISSUE TITLE
FR: `git meta status` should print every open submodule

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#38]
I think `git meta status --summary` is supposed to do this, but (a) that doesn't work, and (b) it's counterintuitive that the _summary_ is _more_ verbose. I think our users will expect to see a list of every codebase from `git meta status` and the current "brief" behavior should be an option.

**Comment by bpeabody** [comment]
I think 'summary' may be the wrong word for that output. We do need an easy way to see all open sub modules, maybe as a separate command or an option to status. 

The 'status' command, itself, gives information about changes to potentially be committed; I don't think it should show unchanged open submodules any more than it should show unchanged paths. It's modeled after 'git status', which has the following as the first paragraph in its documentation:

Displays paths that have differences between the index file and the current HEAD commit, paths that have differences between the working tree and the index file, and paths in the working tree that are not tracked by Git (and are not ignored by gitignore[5]). The first are what you would commit by running git commit; the second and third are what you could commit by running git add before running git commit.

**Comment by bpeabody** [comment]
My proposal:
- change `--summary` to `--list-submodules`
- add a `-a` or `--all` option to `git meta status` that will list all open submodules, even the ones without modifications

**Comment by bpeabody** [comment]
Or we could do what @jhedwardyang did in this PR https://github.com/twosigma/git-meta/pull/39#event-670908128, and leave `status` alone but make the `--summary` command print only open submodules by default. I'm going to recommend changing that to `--list-submodules` while we're at it.

**Comment by jhedwardyang** [comment]
Closing this since it was fixed.
