### ISSUE TITLE
Forward more commands

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#417]
There's currently a small set of forwarded commands:
at https://github.com/twosigma/git-meta/blob/13120986efc8dc5cc8ca82cb9c0070d085977a5f/node/lib/cmd/forward.js#L74
I see "branch, fetch, remote, tag".

We should probably forward lots more. Users will expect them to be there. (one just complained about "show").

Maybe forwarding should be blacklisted rather than whitelisted? Then as git itself gains new commands they will get forwarded automatically?

**Comment by bpeabody** [comment]
If we had a list to blacklist, we could do it, but we don't. Feel free to add many more though (or ask @novalis or me to),

**Comment by bpeabody** [comment]
@s-xiang : come up with a list of all commands we aren't, but should be, forwarding

**Comment by abliss** [comment]
"rev-parse" would be a nice one to forward too.

**Comment by abliss** [comment]
Also requests for "diff".

**Comment by bpeabody** [comment]
Yes, I was thinking about `diff`. My only hesitation was that we might want to do something that wasn't just forwarding to `git diff`, like giving you a mono-repo view of the diff.

**Comment by bpeabody** [comment]
Yes, actually the user was requesting a mono-repo style diff,
