### ISSUE TITLE
git meta submodule find-meta is slow

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#429]
I just did a find-meta for a commit that was only 1.5yrs old, and it took 162sec. Is it perhaps doing a sequential search back through meta history, rather than a binary search? Or perhaps not caching the descendancy bitmap in the submodule?

**Comment by bpeabody** [comment]
I'm pretty sure it's doing something unintelligent. Let me see if I can do something a little better.

**Comment by bpeabody** [comment]
Can go back and change to a binary search later if we have to, but since it's O(N) to start the binary search, we could end up making the normal case (i.e., where the commit is fairly new) slower that way.
