### ISSUE TITLE
FR: "git meta rm"

### ISSUE THREAD

**Issue by abliss** [twosigma/git-meta#440]
Resolve the argument's path-prefix to a submodule, then pass the rest on to "git rm".

**Comment by bpeabody** [comment]
It’s more complicated than that, as it should be able to target any path in the monorepo tree, not just a single submodule. We’ve already got most of the support for doing that though, prior to handing off to libgit2

**Comment by bpeabody** [comment]
https://github.com/twosigma/git-meta/issues/378
