### ISSUE TITLE
git meta pull --rebase doesn't work with untracked-but-ignored files present

### ISSUE THREAD

**Issue by s-xiang** [twosigma/git-meta#523]
1. add a new ignored file:
$ touch my/sub/module/.gitignored-file
2. Nothing appears in git meta status
$ git meta status
On branch master.
nothing to commit, working tree clean
3. $ git meta pull --rebase upstream master
Error: unstaged changes exist in workdir
    at Error (native)

**Comment by novalis** [comment]
This is probably due to https://github.com/twosigma/git-meta/pull/510

**Comment by bpeabody** [comment]
I don't think it's related to #510, rebase doesn't exercise that codepath, and it would in any case cause a non-native error to be thrown.

**Comment by bpeabody** [comment]
There must be something more specific to this than "just" untracked-but-ignored. Won't almost all repos being worked on have untracked ignored files in them?

**Comment by novalis** [comment]
You're right -- something else must be going on here, because I can't immediately reproduce this locally.
