### ISSUE TITLE
allow `root` to take a path argument

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#531]
It would be nice for the command to take a path argument, so that
I don't have to use

root=$(CDPATH= cd $place && git-meta root)

**Comment by novalis** [comment]
Does git -C meta root work?

On April 9, 2018 11:47:18 AM EDT, Brock Peabody <notifications@github.com> wrote:
>It would be nice for the command to take a path argument, so that
>I don't have to use
>
>root=$(CDPATH= cd $place && git-meta root)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/twosigma/git-meta/issues/531

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bpeabody** [comment]
It does, indeed, work.
