### ISSUE TITLE
`push` should be smart about which submodules to push

### ISSUE THREAD

**Issue by bpeabody** [twosigma/git-meta#539]
# Overview

Currently, `push` pushes all open submodules, every time. Even though these pushes happen in parallel, it's pretty slow. Instead, it should push only submodule commits that don't exist upstream. If such a commit is in a closed submodule, it should push that submodule too -- but only if it exists in `.git/modules` -- there's no reason to fetch down a commit and then push it. We could check against all remote refs, but that could be prohibitively expensive (e.g., if you have hundreds of remote refs). Instead, we'll do something that does the right thing most of the time, and pushes too much when it is wrong rather than too little:

# Plan

1. Start with the set of submodules that are either open, *or* that exist in `.git/modules`. Populate a `pushMap` from submodule name to commit (SHA) registered in the meta-commit being pushed.
2. If the push target exists in `remotes/$remote/$branch`, remove from `pushMap`, any entry where the commit for a submodule already exists in the target.
3. Note that for "exists" we mean the target points to exactly the commit needed or a descendant of that commit.
4. If the user is pushing a branch, B, further reduce the size of `pushMap` by removing commits referenced in the branches that B pulls from and/or pushes to by default, if they exist and are different from the target branch.

Thus, in the best case, we will push only submodule commits that have been created locally and never pushed. In the worst case, e.g., if the user creates a branch with no tracking information and pushes to a new branch, we will do a push for every open and "half" open submodule. The next time the user pushes to this branch we will push a minimal set. Unlike today, we will in any case push the submodules that the user has closed if they still exist in `.git/modules` and have potentially unpushed commits. There are ways the user could still get into an unpushable state, e.g., `rm -rf .git/modules/$sub-name`, but we will eliminate the most common situation with this change.

# Implementation Notes

* You can get the SHAs referenced by a commit with `SubmoduleUtil.getSubmoduleShasForCommit`. This method takes a list of names of the submodules you're requesting; you should make that list minimal (i.e., only candidate submodules) to improve performance.
* Support will need to be added to manipulate submodules that are not open but that do exist in `.git/modules`, e.g.:
    * listing them
    * opening their repositories without actually opening them (checking out their files in the work tree)
* With such support, we would ideally not need to open these submodules to push their commits. We could port this ability back to such operations as `merge`, perhaps never fully opening them unless we need to do real work. E.g., if we determine a submodule merge operation can be fast-forwarded we would "half" open it, but when we need to create a merge commit we will have to fully open it. (I'll make a ticket for this if it looks possible).

**Comment by novalis** [comment]
I think that looks good to me.
