### ISSUE TITLE
commit --amend broken with merge commits -- it amends any commits not on the LHS rather than just those introduced by the one being amended

### ISSUE THREAD

**Issue by novalis** [twosigma/git-meta#598]
If you git meta commit -a --amend on a merge (or any?) commit, it will attempt to open up all codebases affected by the commit.

**Comment by bpeabody** [comment]
How is it going to amend them without opening them first?

**Comment by beethoven2493** [comment]
I don't think that's the answer. Let's say I do the opposite, ie I merge my new branch into default. Only 1 codebase is relevant in that merge. Then looking vs the first parent makes sense too.

"git meta merge" seems to say "Oh gee, only 1 codebase needs to be opened here". Is that because it has the opposite reference as commit? Or because it has some smarter intersection-only logic?

**Comment by bpeabody** [comment]
Good point @beethoven2493 . Maybe the answer is that it needs to look at submodule commits that don't exist in any of the parents of the commit being amended.

**Comment by novalis** [comment]
commit --amend never needs to open any submodules -- only already-open submodules can have changes to be committed.

**Comment by bpeabody** [comment]
That's not necessarily true, @novalis. What if I make a new clone, pull down one of my branches, and decide to amend the last commit?

**Comment by novalis** [comment]
How are you making any changes if you don't already have the codebase open?

**Comment by beethoven2493** [comment]
@novalis That is a really good point. Kind of hard to make local changes / stage changes if the codebase isn't open.

**Comment by bpeabody** [comment]
You still need to apply the update to the commit message.

**Comment by novalis** [comment]
I guess we could skip it for the --no-edit case too.  But skipping in the merge cases seems good anyway.

**Comment by bpeabody** [comment]
1. I think in the merge case what we're doing is just plain wrong; we're going to be making amends that shouldn't be made.
2. In the "normal" case, we do need to open submodules to perform sanity checking and update commit Messages.
3. If `--no-edit` is specified we could probably skip them. This will be a slight change from Git, which would update the committer (date and author) if you ran `--amend --no-edit` in a repo with no changes, but I think it probably makes sense. However, I don't think we really need to do anything here at this time -- if not for the bug in (1) we wouldn't be having this discussion.

**Comment by bpeabody** [comment]
I mean to say that what git-meta does in this case is completely wrong and we need to fix it asap.
