### ISSUE TITLE
Provide a 'git meta diff' command

### ISSUE THREAD

**Issue by nkicillof** [twosigma/git-meta#63]
This command should be implemented in terms of `git diff`. The only reason we need an explicit command (rather than relying on our normal forwarding) is that we will provide the `--submodule=diff` option, forwarding all other arguments.

**Comment by bpeabody** [comment]
I'm guessing this would look just like `git diff` except that we would infer submodule from specified paths. The specified commits would be meta-repo commits.

**Comment by bpeabody** [comment]
So, given a submodule `x/y`:
```bash
git meta diff HEAD^ x/y/README.md
```
Would output a diff between the `README.md` file in the working directory of `x/y` (if modified, `HEAD` otherwise) and the `README.md` file in the commit indicated for `x/y` in the previous commit of the meta-repo.

**Comment by nkicillof** [comment]
Thanks Shihui!
