### ISSUE TITLE
Architecture clarification WRT Android Repo

### ISSUE THREAD

**Issue by sschuberth** [twosigma/git-meta#634]
While going through [Why doesn't everyone have a mono-repo?](https://github.com/twosigma/git-meta/blob/master/doc/architecture.md#why-doesnt-everyone-have-a-mono-repo) I've noticed several statements that I believe to be incorrect, and I'd like to get some understanding how you came to these conclusions, and eventually correct them.

To start with, there is nothing Android-specific about "Android Repo", how you call it. While it's true that the tool was developed in the context of Android, we use it for several non-Android projects. The upstream repository is actually called [git-repo](https://gerrit-review.googlesource.com/admin/repos/git-repo) (no mention of "Android" there), and that's the term I personally prefer.

> most don't provide a way to reference the state of all repositories (Gitslave, Android Repo, Myrepos)

That's not true, as you can use tags / fixed SHA1s inside `manifest.xml` (also see [repo manifest -r](https://stackoverflow.com/questions/33030289/is-there-a-tool-to-create-repo-manifest-file-with-sha-based-on-current-work-dire)). The committed state of such a fixed / baked manifest then describes the state of all repositories.

> some require a custom server (Android Repo)

That's also not the case. `manifest.xml` files are hosted in regular Git repositories, and we successfully [use "Android Repo" with GitHub](https://github.com/heremaps/oss-review-toolkit-test-data/tree/master/git-repo).

> many are strongly focused on supporting a specific software platform (Android Repo, gclient)

Do you mean host or target platform? In any case, as already outlined above, "Android Repo" is *not* Android-specific. However, for a long time it was not running at all on Windows as a host platform, but that has changed with the upstream `master` version (no `stable` release yet, however).

Don't get me wrong, I'm not saying "Android Repo" is the better tool. But if you want to convince people to move from "Android Repo" to *git-meta* the comparison should be fair.

**Comment by bpeabody** [comment]
Hi Sebastian,

Thanks for your feedback! I think a lot has changed with git-repo (I will stop calling it Android Repo!) since I last looked at it (and maybe I was just confused about some things to begin with). I will update this document to remove the inaccuracies you pointed out.

**Comment by sschuberth** [comment]
Thanks @bpeabody. I added some minor comments to the PR directly, even if it's already merged. Anyway, I believe the statements WRT git-repo to be correct now, so I'm closing this. Thanks again!

**Comment by bpeabody** [comment]
Thanks again @sschuberth (also made https://github.com/twosigma/git-meta/pull/640 to fix the typos you pointed out).
