### ISSUE TITLE
git-meta checkout to the branch that is not aware of submodule that's open locally

### ISSUE THREAD

**Issue by zokir** [twosigma/git-meta#667]
Lets say if I have a submodule that is open locally and then I decide to checkout a branch that is not aware of this submodule. Should this submodule be left open as it happens now, or should we close this submodule and fail to checkout if it has uncommitted changes?

**Comment by novalis** [comment]
The latter, IMO.

**Comment by bpeabody** [comment]
I disagree. That approach creates problems when the "checkout" is part of an intermediate operation, e.g., a rebase. Further, Git will never "close" a submodule due to a change in HEAD, whether there are uncommitted changes or not, e.g.:

```bash
$ write-repos -o 'a=B|x=U:Os;Bold=1'
$ cd x
$ git checkout old
warning: unable to rmdir 's': Directory not empty
Switched to branch 'old'
```

**Comment by bpeabody** [comment]
We could give a warning like Git does though.
