### ISSUE TITLE
Problem running `pull --rebase origin master`

### ISSUE THREAD

**Issue by meredian** [twosigma/git-meta#680]
Hello!

I've encountered consistent problem, while trying to run typical git pattern. When running `meta git pull --rebase {remote} {branch}`, `git-meta` instead runs `git pull {branch} --rebase {remote}`, which is not a working thing.

Git version 2.17.0
Os: MacOS 10.13 (`Darwin 17.7.0 Darwin Kernel Version 17.7.0`)

Here's specific example output:
```
➜  meta git:(feature/xxxx) ✗ meta git pull --rebase origin master

meta:
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
meta: command 'git pull master --rebase origin' exited with error: Error: Command failed: git pull master --rebase origin
```

I would like to deal with issue on my own, since it will make my life much easier :)
1) Please confirm it's a bug, or it should be done in some other way.
2) Maybe there are any use cases, when this behaviour is correct, so I do not miss them?
3) Any recommendations on contributing to the code are welcome, but not mandatory :)

**Comment by bpeabody** [comment]
Hi Anton,

I suspect you may be looking at the wrong project. You can't invoke (this) git-meta command as `meta git`; it's either `git-meta` or `git meta`. If I do give an unknown remote, I get something like:

```bash
$ git meta pull --rebase foo bar  # where foo doesn't exist
Invalid remote name foo.
```

In any case, I'm very curious about what `meta git` is if it's not `git meta` :)

**Comment by meredian** [comment]
@bpeabody Haha, seems like I really messed, sorry for your time 😄 Yep, correct project was that one: https://github.com/mateodelnorte/meta-git :) That's a plugin for https://github.com/mateodelnorte/meta - very simple tools that follows generally same pattern, as `git-meta` does. Used in a company I joined recently. But it still brings some submodule-based complications and feels to low-level. So I'm glad to discover your project, will investigate it. And you have a great into doc!

**Comment by bpeabody** [comment]
Thanks, and no worries, @meredian. It was interesting to learn about the `meta` tool; I introduced myself to its author in case he gets an issue from someone running `git meta` instead of `meta git` :)

Please hit me up if you have any questions about git-meta!
