### ISSUE TITLE
git meta commit -m works differently than git commit -m

### ISSUE THREAD

**Issue by tslally** [twosigma/git-meta#714]
`git commit` allows you to specify `-m` more than once: `If multiple -m options are given, their values are concatenated as separate paragraphs.`. It looks like `git meta commit` only uses the last message :disappointed:

**Comment by kaaniboy** [comment]
Looks like this one has already been fixed. For example, running `git meta commit -m "a" -m "b" -m "c"` gives:

```
commit 1234567890 (HEAD -> master)
Author: Kaan <...>
Date:   Fri Sep 25 16:48:48 2020 +0000

    a

    b

    c
```

**Comment by brown** [comment]
Yes, this issue has been fixed.
