### ISSUE TITLE
git meta cherry-pick does not explain next steps on conflict

### ISSUE THREAD

**Issue by rgeary19** [twosigma/git-meta#719]
When a git meta cherry-pick fails with a conflict, the user is only told that there is a conflict in a submodule.  No further instructions are given.

I would expect that the error message would include information on `git meta cherry-pick --continue` and `git meta cherry-pick --abort`

**Comment by brown** [comment]
Fixed by 8afd587ea31ac57c9e1ac1a2e7f39271b96486b3
