### ISSUE TITLE
git meta push should fail if pushing subproject detached commits

### ISSUE THREAD

**Issue by jhdub23** [twosigma/git-meta#723]
Although it's possible to add commits within a submodule when in a detached HEAD state, a normal "git push" within the submodule will fail with the error message:

```
# fatal: You are not currently on a branch.
# To push the history leading to the current (detached HEAD)
# state now, use
#
#     git push origin HEAD:<name-of-remote-branch>
```

However, "git meta push" will happily succeed, and you will be left with a dangling commit within the subrepo.  At some point, that dangling commit will be garbage collected, leaving your history in a broken state.

"git meta push" should only succeed if submodule commits can be pushed onto the current branch that is checked out within the submodule, and fail if the commits are in a detached HEAD state.

To reproduce, see the sequence of commands (assuming you have repos "meta" and "proj_foo"):

```
mkdir u1 u2
pushd u1
git clone ../Gitserver/meta.git
cd meta
git submodule add ../proj_foo.git
git meta commit -a -m "Added proj_foo submodule"
git meta push
popd

pushd u2
git clone ../Gitserver/meta.git
git meta open proj_foo
cd proj_foo
date >> README
git add README
git commit -m "date1 u2"
git push
# fatal: You are not currently on a branch.
# To push the history leading to the current (detached HEAD)
# state now, use
#
#     git push origin HEAD:<name-of-remote-branch>
cd ..
git commit -a -m "date1 u2 meta"
git meta push
# Succeeds, when it should fail

```

**Comment by abliss** [comment]
If `git meta push` succeeded, you should find that it successfully pushed
your submodule commit's detached HEAD to a "synthetic meta ref" like
`refs/commits/$SHA1`. This prevents it from getting GC'd on the remote host.

**Comment by abliss** [comment]
See https://github.com/twosigma/git-meta/blob/master/doc/architecture.md#synthetic-meta-refs for more details. If you're not seeing them on your remote submodule, then let us know, that's a bug!

**Comment by abliss** [comment]
Also note that, in general, git-meta expects you to have detached heads (and no branches) in your submodules. (You can use branches if you want, but git-meta will ignore them.) See the architecture doc for details on why.

**Comment by jhdub23** [comment]
Ok, I was looking for the "refs/meta" directory based on the docs.  It looks like the synthetic refs are in "refs/commits."  Is this correct?

**Comment by jhdub23** [comment]
Doc should be updated to replace "refs/meta" with "refs/commits".

**Comment by abliss** [comment]
Thanks!
