### ISSUE TITLE
git-meta open does not work with relative paths in .gitmodules

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#76]
**Directory structure:**
- meta
.gitmodules
submodule1 _(git submodule add ../submodule1)_
submodule2 _(git submodule add ../submodule2)_ 
- submodule1
- submodule2

**Repro steps:**
1. Clone meta
2. git meta open submodule1

**Expected:**
Will open submodule1. _(git submodule update --init submodule1)_

**Actual:**
Fails and leaves repository in a bad state.

**Comment by jhedwardyang** [comment]
> $ git meta open submodule1
> Error: Object not found - no match for id (a1c495e19974584f93ad6f88933f0a28fe61f39)
> $ git meta open status
> No head commit.

**Comment by bpeabody** [comment]
You mean a relative URL? Can you zip up an example of this setup?

**Comment by bpeabody** [comment]
should be fixed now
