### ISSUE TITLE
git-meta status still shows submodules being expected on a branch

### ISSUE THREAD

**Issue by jhedwardyang** [twosigma/git-meta#82]
meta is on branch foo.
submodule1 is in detached head. 

```
$ git meta status
On branch foo.
nothing to commit, working directory clean
Submodules:
submodule1
Expected to have foo but is not on a branch.
```

**Comment by bpeabody** [comment]
I think this is correct behavior according to the original design of git-meta, but wrong according to our new design. We can leave this here as a reminder that it needs to be fixed in the rebranding.

**Comment by bpeabody** [comment]
should be fixed now
